{% set name = "sphinx-releases" %}
{% set version = "1.6.0" %}
{% set sha256 = "0120206ec0304eea0bfbff1a3d6f96f71ffdd719de49bfdb6f0ac9f7896a8b3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bitprophet/releases/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - semantic_version
    - sphinx

test:
  imports:
    - releases

about:
  home: https://github.com/bitprophet/releases
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A powerful Sphinx changelog-generating extension
  doc_url: http://releases.readthedocs.io/
  dev_url: https://github.com/bitprophet/releases

extra:
  recipe-maintainers:
    - kwilcox
