{% set name = "sphinx-releases" %}
{% set pypi_name = "releases" %}
{% set version = "1.6.3" %}
{% set sha256 = "555ae4c97a671a420281c1c782e9236be25157b449fdf20b4c4b293fe93db2f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - semantic_version
    - sphinx

test:
  imports:
    - releases

about:
  home: https://github.com/bitprophet/releases
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A powerful Sphinx changelog-generating extension
  doc_url: http://releases.readthedocs.io/
  dev_url: https://github.com/bitprophet/releases

extra:
  recipe-maintainers:
    - kwilcox
