{% set name = "sphinx-releases" %}
{% set pypi_name = "releases" %}
{% set version = "2.1.0" %}
{% set sha256 = "1303b87d6f0427fbdcc40c31bb893b1dab5be4c8619a4b1c2710c0a218e3c79c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - semantic_version <2.7
    - sphinx >=1.8

test:
  imports:
    - releases

about:
  home: https://github.com/bitprophet/releases
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A powerful Sphinx changelog-generating extension
  doc_url: http://releases.readthedocs.io/
  dev_url: https://github.com/bitprophet/releases

extra:
  recipe-maintainers:
    - kwilcox
