travis:
  secure:
    BINSTAR_TOKEN: vLnBEB6vwoCZXRRHQ4WfQiroqCkyhGLMzVKBMXInnBshPeMziZJE3Yzz3B24Z9GcLNUE2WwvPtbmiQEO/iX8g3GICvOQzkSEZMNu0IpzCM4J29W/8prhravXvecne4mJ5GLu24IKwiRCY+pyHCDN/FfRnZUprH1/BCQNysug7DkJAucRUmTAbqVh0Mby1wUOcRodXnzq8zpu93nwwx9stGkKx/5FJcCRdBwb9q3iCcgLDt3bRNPI96fCZgyJ+j4soLy21T9+D+qWkENb+qJJaREMVulskyskC3549EBH1RgIxbeFgbKUF4n9FOoV6UM83UWMT/6CHQhy4SMqtU6uAxlPcER+A3Y6L+dyfbfGxBnKf/trULZssz3Fmm2Jg0u8XFXgrcmU7I6OiooyamQAZiLrAXUf3g/SvwXjOST2iKTNg7oOXsDUrIVJrEWfJGPE66nyh2JWhKfV67CDLbE7KdzpnohOodVGdRrlahUj8qSMDVSVYDSs0hGkN/iAP9BD/yek9j0ttoUE4jgg4TIPQkGXPqDTguFERx1ZI6j7Fgk8ebXAXU0pKCyAK7XI6msPN/oZjOtLiMBFa7Vgq1yPcOOS+iXF0drH2aLbXLPY1x8NqZOIuRru1FURjqRAhB22ZJ5piRn4SoEfxBlpdLyHLR7KdJWa5/7udLe+y6VqvTU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
