travis:
  secure:
    BINSTAR_TOKEN: 7v5J8Sr4DftPSeR30ERbwebbvTiA3fTOMJdMW076oZcYoj3tzCeqj7dnX+TnEFdyAWz8mOxyIVkg2PQh5/ycALOR1EWG7UIyEURP325JsfiUuSYskRqa1OC32NorEU7xI0GSPMHaG/ZnqIjEX98KCS1yZkoTe1jJhv8WfutmiLanrnYkNYb/2BXrso6VrnavK9cyOzTlpcWlMNPFvcLPTEeVNMOVBLyEF54sDkAzJrEsEdsU6AxZ27ji8qW6pOTviojnYZrk50zHVCZDNe93ieCIySjYVarqPQ8LLD1CyiGXE/J47XOWqOPdwU7lpBr+5Xxu+T8rQKYug+LpThC2Imk6UP0dVNIkSBeWA2jmXS9DwSDjisgvq7UbFSDanh5jD4vizAQTtU4EuLJyzIvqgByucYji6OvQ0f4GBPzVEs97BDP5vixtqMg+wJ7JgL5mwGp0p3IdNaBLKr/HkgcAAfpLGZYvoaAPJIeyaYg5ikDmhaHRn574nsNjqnlv6ppTwdVeDvPH4Pf2SFmMsEqo1vFOiPLl5GmY/2kKfVEfX/3Cl5uyxD79YN7Ex6xbPop9u7cf6TmXwTSZom09jv3VmaAPeqhh9u72ygUkj17pxiK6vZ69UktZ6iykUHgcdlnUmATb9Uho4ngNG1rOJiUlrDMzcpg0mDUOLFMhSVc/3hI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
