travis:
  secure:
    BINSTAR_TOKEN: L/uM+uxjPggUhM+fqHPotpJZ/YIjBfV1Tvoc3qi1doz1S5pEClYD4rK4LFv6myPHL0uSY358oT6C7tsaofXhLrcFao8wnUHg63Ujx1uuF/Ws4Ku0y00GgDHGZeNgCN1//YVH39Wh8SbxJCdPmbWUb/p7BOgP2DMuFWLAWd6A7KnrEB9FnTPbNLNfQpKEnrprIY95Vdcmc+72TrC0dratWGAgCgWv0G0ZKLIn0/+8RB8msy/yI5zucbuNNvcgIfKq9WosUQo1TdSO0A0D/7+jj4WtqiUdng5CBhGRZTgGbhcJTW6pKlJGOmzQVaTPNZRdh6/LFMgWFMNeq2tHnJ+GVCaZqWRgMaPxTmg83IDsCNSiWKICa+k/o01t9zFAnNgo0009at+PjQVQ7jEFlYmmk2154maICS/v8E7QxLrbMdjf9soWW70R++bkDEE5lsTDeE3PzqDTDnwbgWbCqkIxZFEXSIYVb3Wg7FAi0N0LzF1e7rFMuSomcm+vmc3OpPHlEmCIvzXHark4LE0HqsoLFcNNc0oES+/5iBT1NyArWwbV/V6TZdZhzVMlgvPCAxSD8ToZbcZOKOIueE31uhYQ2JXX4VSlsNoNUWNipIhEhW6ie9G8xGehgI4Wt2f3kiueYpl6Ne+N3S0/Qei7ThdPXXtEActmJzj3eWNkbNMAraQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
